export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const PRODUCT_FETCH_BEGIN = "PRODUCT_FETCH_BEGIN";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_ERROR = "PRODUCT_FETCH_ERROR";
export const SINGLE_PRODUCT_BEGIN = "SINGLE_PRODUCT_BEGIN";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";
